language: c
compiler: gcc

# Package installation
before_install:
  - export CC="gcc-4.8";
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - valgrind

# Run only on the master branch
branches:
    only:
        - master

# Build a test binary and run tests
script: make -C source test

